fix(docs): Fix duplicate attribute error (#712)
If using the original example snippet, you get an `already defined`
error.

```sh
 error: attribute 'den.schema.host' already defined at /nix/store/ylfa8wp9kmqcys3g39y8nddd0qsz27z3-source/modules/config/nixpkgs/home-manager.nix:14:3
       at /nix/store/ylfa8wp9kmqcys3g39y8nddd0qsz27z3-source/modules/config/nixpkgs/home-manager.nix:20:3:
           19|   };
           20|   den.schema.host.includes = [den.aspects.home-manager-shared];
             |   ^
           21|
```

This PR removes the duplicate by merging `den.schema.host.includes` into
`den.schema.host` itself.

The fix also makes the den schema use the top level `lib` instead of the
module provided one. It works fine from my testing, but thought I should
mention it.